name: frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  anim_search_bar: ^2.0.2
  cupertino_icons: ^1.0.2
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^12.0.2
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  google_fonts: ^2.3.2
  http: ^0.13.5
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  mongo_dart: ^0.7.4+1
  qr_code_scanner: ^1.0.0
  sign_button: ^2.0.2
  toggle_switch: ^2.0.1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_foreground: "assets/icons/logo_foreground.png"
  adaptive_icon_background: "#FAF9F6"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: GenJyuuGothic
      fonts:
        - asset: assets/fonts/GenJyuuGothic-Bold.ttf
          weight: 900
        - asset: assets/fonts/GenJyuuGothic-Heavy.ttf
          weight: 700
        - asset: assets/fonts/GenJyuuGothic-Medium.ttf
        - asset: assets/fonts/GenJyuuGothic-Light.ttf
          weight: 300
        - asset: assets/fonts/GenJyuuGothic-ExtraLight.ttf
          weight: 200
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
    - family: MontserratSubrayada
      fonts:
        - asset: assets/fonts/MontserratSubrayada-Bold.ttf
          weight: 900
        - asset: assets/fonts/MontserratSubrayada-Regular.ttf
          weight: 800
    - family: GenRyuMin
      fonts:
        - asset: assets/fonts/GenRyuMin-B.ttc
          weight: 800
        - asset: assets/fonts/GenRyuMin-SB.ttc
          weight: 700
        - asset: assets/fonts/GenRyuMin-H.ttc
          weight: 600
        - asset: assets/fonts/GenRyuMin-M.ttc
          weight: 500
        - asset: assets/fonts/GenRyuMin-R.ttc
          weight: 400
        - asset: assets/fonts/GenRyuMin-L.ttc
          weight: 300
        - asset: assets/fonts/GenRyuMin-EL.ttc
          weight: 200
