// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpe26QDR8VrCDWgXlkQUIsQh_0edlGMKk',
    appId: '1:432955737562:android:686a7a27275df16a37ece3',
    messagingSenderId: '432955737562',
    projectId: 'savefoodbattle-1',
    storageBucket: 'savefoodbattle-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFzgTE_kPQWZ__jTo5mamBHGCcI01WJfs',
    appId: '1:432955737562:ios:4c33a3dc9a867db337ece3',
    messagingSenderId: '432955737562',
    projectId: 'savefoodbattle-1',
    storageBucket: 'savefoodbattle-1.appspot.com',
    androidClientId: '432955737562-lhmj8igp624v030k73qthrskgul2fa6k.apps.googleusercontent.com',
    iosClientId: '432955737562-3bvust5tl9tcm6qnvofbom81i3ku5qjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
